[pytest]
addopts = -v --tb=short --strict-markers --strict-config
testpaths = .
filterwarnings =
    error::pytest.PytestUnknownMarkWarning 
markers =
    smoke: critical happy-path tests
    regression: broader feature tests
    alerts: tests that include alerts
    deprecated: Edge cases that no longer work
    iframe: tests that need to get into iframe
    robust_version: la robust version
    hover: hover tests
    auth: authentication/authorization api tests
    api: api tests
    rainyday: Rainy Day Tests


    # filter warnings turns unmkown markers into erros instead of a waring make ir cleaner not necessary beacause --strict-markers 